### PR TITLE
fixing original - see tests

### PR DESCRIPTION
**Pull request by mbcheikh**

### CODE REVIEW

**Comment by camilonova** [comment]
@vero4karu Can you review this one?

**Comment by mbcheikh** [comment]
Ok, I synced my fork and tests are good. This pull will allows:
 
- to use string constants (quoted  by ') as in js-expression-eval
- to use concat function with many arguments instead of only 2.

**Comment by vero4karu** [comment]
@camilonova

**Comment by camilonova** [comment]
Beautiful. Thanks.

**Comment by vero4karu** [comment]
I just uploaded a new version to pypi: https://pypi.python.org/pypi/py_expression_eval/0.3.1

**Comment by PabloVallejo** [comment]
Sweet! 👍

**Pull request merged**
