### PR TITLE
Support '**' as power operator

### LINKED ISSUE #42: power operator '**' not working
Below codes are expected to return val as 8.0

```python
from py_expression_eval import Parser
parser = Parser()
val = parser.parse('x**3').evaluate({'x': 2})
```

However it ran into error as follows:
```
Traceback (most recent call last):
  File "/home/kang/apps/pycharm-community-2018.1.1/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/kang/apps/pycharm-community-2018.1.1/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/kang/apps/pycharm-community-2018.1.1/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/kang/gh-hyperkang/pylib/pyfem-ansys/pyfem_ansys/cdb/ansys_utils.py", line 154, in <module>
    print parser.parse('x**3').evaluate({'x': 2})
  File "/home/kang/gh-hyperkang/pylib/py-expression-eval/py_expression_eval/__init__.py", line 493, in parse
    self.error_parsing(self.pos, 'parity')
  File "/home/kang/gh-hyperkang/pylib/py-expression-eval/py_expression_eval/__init__.py", line 503, in error_parsing
    raise Exception(self.errormsg)
Exception: parse error [column 4]: parity
```

### PR DESCRIPTION
**Pull request by hyperkang**
fix #42

### CODE REVIEW

**Comment by vero4karu** [comment]
Thank you!

**Comment by hyperkang** [comment]
> Thank you!

My pleasure!

**Comment by vero4karu** [comment]
@hyperkang Here is a new version with the changes from your PRs: https://pypi.org/project/py-expression-eval/0.3.7/ :slightly_smiling_face:

**Comment by hyperkang** [comment]
> @hyperkang Here is a new version with the changes from your PRs: https://pypi.org/project/py-expression-eval/0.3.7/ 🙂

Cool~  :smile:

**Pull request merged**
