### PR TITLE
Adding if function (like the js version)

### PR DESCRIPTION
**Pull request by mbcheikh**
if (a,b,c) equivalent to a?b:c in js,, and to b if a else c in python

### CODE REVIEW

**Comment by camilonova** [comment]
Thank you

**Comment by laurence-hudson-mindfoundry** [comment]
Could this please make its way into a released version?

**Comment by vero4karu** [comment]
@laurence-hudson-mindfoundry Done: https://pypi.org/project/py_expression_eval/0.3.5/

**Comment by laurence-hudson-mindfoundry** [comment]
Perfect, thanks!

**Pull request merged**
